#!/bin/bash

if [[ "${DEBUG}" == "true" ]]; then
	echo "[debug] Attempting to read /tmp/getvpnip ..."
fi

while [ ! -f /tmp/getvpnip ]
do
	sleep 0.1s
done

if [[ "${DEBUG}" == "true" ]]; then
	echo "[debug] Found file with VPN IP under /tmp/getvpnip"
fi

# get vpn tunnel ip address (file contents generated by /root/getvpnip.sh)
vpn_ip=$(</tmp/getvpnip)

if [[ "${DEBUG}" == "true" ]]; then
	echo "[debug] Valid local IP address from tunnel '${vpn_ip}'"
fi
